/******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_Lcfg.c
 *
 * Description: Link time Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Team9 
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (3U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (1U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = 
{
  PORT_A_ID, PIN_0_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_A_ID, PIN_1_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_A_ID, PIN_2_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_A_ID, PIN_3_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_A_ID, PIN_4_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_A_ID, PIN_5_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_A_ID, PIN_6_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_A_ID, PIN_7_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  
  PORT_B_ID, PIN_0_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_B_ID, PIN_1_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_B_ID, PIN_2_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_B_ID, PIN_3_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_B_ID, PIN_4_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_CAN, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_B_ID, PIN_5_ID, PORT_PIN_OUT, OFF, PORT_PIN_MODE_CAN, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_B_ID, PIN_6_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_B_ID, PIN_7_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  
  /*JTAG PINS will not be configured PC[0:3] Tiva C has total 43 Pins but without JTAG pins 39pins*/
  //PORT_C_ID, PIN_0_ID,PORT_PIN_IN,OFF,PORT_PIN_MODE_DIO,INSTANCE_0,PORT_PIN_LEVE_LOW,STD_OFF,STD_OFF, 
 // PORT_C_ID, PIN_1_ID,PORT_PIN_IN,OFF,PORT_PIN_MODE_DIO,INSTANCE_0,PORT_PIN_LEVE_LOW,STD_OFF,STD_OFF, 
 // PORT_C_ID, PIN_2_ID,PORT_PIN_IN,OFF,PORT_PINL_MODE_DIO,INSTANCE_0,PORT_PIN_LEVE_LOW,STD_OFF,STD_OFF,
 // PORT_C_ID, PIN_3_ID,PORT_PIN_IN,OFF,PORT_PIN_MODE_DIO,INSTANCE_0,PORT_PIN_LEVE_LOW,STD_OFF,STD_OFF
  PORT_C_ID, PIN_4_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_C_ID, PIN_5_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_C_ID, PIN_6_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_C_ID, PIN_7_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  
  PORT_D_ID, PIN_0_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_D_ID, PIN_1_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_D_ID, PIN_2_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_D_ID, PIN_3_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_D_ID, PIN_4_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_D_ID, PIN_5_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_D_ID, PIN_6_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_D_ID, PIN_7_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  
  PORT_E_ID, PIN_0_ID, PORT_PIN_IN,OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_E_ID, PIN_1_ID, PORT_PIN_IN,OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_E_ID, PIN_2_ID, PORT_PIN_IN,OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_E_ID, PIN_3_ID, PORT_PIN_IN,OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_E_ID, PIN_4_ID, PORT_PIN_IN,OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_E_ID, PIN_5_ID, PORT_PIN_IN,OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  
  PORT_F_ID, PIN_0_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVEL_HIGH, STD_OFF, STD_OFF,
  PORT_F_ID, PIN_1_ID, PORT_PIN_OUT, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_F_ID, PIN_2_ID, PORT_PIN_OUT, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF,
  PORT_F_ID, PIN_3_ID, PORT_PIN_OUT, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVE_LOW, STD_OFF, STD_OFF, 
  PORT_F_ID, PIN_4_ID, PORT_PIN_IN, OFF, PORT_PIN_MODE_DIO, INSTANCE_0, PORT_PIN_LEVEL_HIGH, STD_OFF, STD_OFF, 
  				           
};